import './globals.css'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import Navbar from '../components/Navbar'
import Header from '@/components/Header'

export const metadata = {
  title: 'Appli Volley',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const cookieStore = cookies()
  const supabase = createServerComponentClient({ cookies: () => cookieStore});
  const {
    data: { session},
  } = await supabase.auth.getSession()


  return (
    <html lang="en">
      <body>
        <Header user={session?.user} />
        <Navbar user={session?.user} />
        <main className="min-h-screen bg-background flex flex-col items-center">
          {children}
        </main>
      </body>
    </html>
  )
}
